import {
  API_BASE_URL,
  FACEBOOK_APP_ID,
  ANDROID_GOOGLE_CLIENT_ID,
  IOS_GOOGLE_CLIENT_ID,
  EXPO_GOOGLE_CLIENT_ID,
  WEB_GOOGLE_CLIENT_ID,
} from "@env";

const config = {
  API_BASE_URL,
  FACEBOOK_APP_ID,
  ANDROID_GOOGLE_CLIENT_ID,
  IOS_GOOGLE_CLIENT_ID,
  EXPO_GOOGLE_CLIENT_ID,
  WEB_GOOGLE_CLIENT_ID,
};

export default config;
